source 'https://github.com/gaojinhsu/PodTestLibSpecs.git'
source 'http://git.code.oa.com/greysongjxu/TDataMasterSpecs.git'

platform :ios, '8.0'

target 'PodTestLib_Example' do
#  pod 'PodTestLib', :path => '../'
  
   pod 'PodTestLib', '0.4.0'

  target 'PodTestLib_Tests' do
    inherit! :search_paths

    
  end
end
