source 'https://github.com/gaojinhsu/PodTestLibSpecs.git'

platform :ios, '8.0'

target 'PodTestLib_Example' do
  pod 'PodTestLib', :path => '../'

  target 'PodTestLib_Tests' do
    inherit! :search_paths

    
  end
end
